name: Docker Image CI Update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      image_name:
        description: "Choose docker image to update"
        required: true
        default: "heroku"
        type: choice
        options:
          - hikka
          - heroku
          - legacy
          - geektg
  schedule:
    - cron: '0 6 * * *'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set.outputs.images }}
    steps:
      - id: set
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo 'images=["heroku","legacy"]' >> $GITHUB_OUTPUT
          else
            name="${{ github.event.inputs.image_name || 'heroku' }}"
            echo "images=[\"$name\"]" >> $GITHUB_OUTPUT
          fi


  build:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      matrix:
        image: ${{ fromJson(needs.set-matrix.outputs.images) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hikkahost:${{ matrix.image }}
